-- Migration 017: seed standard tosco shop catalog
-- Created: 2026-06-14

INSERT INTO shop_items (item_key, item_name, item_description, price, category, currency_type, is_active)
VALUES
    ('std_001', 'Meia Furada', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_002', 'Pedaço de Pão Mofado', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_003', 'Cueca Velha', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_004', 'Esponja de Banho Usada', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_005', 'Chinelo Quebrado', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_006', 'Casca de Banana', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_007', 'Resto de Pizza Fria', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_008', 'Tampa de Garrafa', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_009', 'Borracha Mastigada', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_010', 'Lápis sem Ponta', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_011', 'Caneta sem Tinta', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_012', 'Papel Higiênico (1 folha)', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_013', 'Cotonete Usado', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_014', 'Pelo de Gato', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_015', 'Catarro Seco', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_016', 'Dente de Leite', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_017', 'Unha Cortada', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_018', 'Bolinha de Poeira', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_019', 'Caixa Vazia', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_020', 'Saco Plástico', 'Item padrao da Loja Tosca.', 100, 'itens_toscos_zoeira', 'lumicoins', TRUE),
    ('std_021', 'Pedra Comum', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_022', 'Pedra um Pouco Diferente', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_023', 'Galho Caído', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_024', 'Folha Seca', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_025', 'Sombra de Alguém', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_026', 'Vento Engarrafado', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_027', 'Silêncio Embalado', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_028', 'Ar Puro (1 respiração)', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_029', 'Eco', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_030', 'Nada (literalmente)', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_031', 'Caixa de Sapato Vazia', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_032', 'Manual de Instruções em Chinês', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_033', 'Pilha Descarregada', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_034', 'Carregador que Não Encaixa em Nada', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_035', 'Fio Desencapado', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_036', 'Ficha de Telefone Público', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_037', 'CD Riscado', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_038', 'Fita Cassete Quebrada', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_039', 'Disquete de 1.44MB', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_040', 'VHS sem Fita', 'Item padrao da Loja Tosca.', 100, 'itens_in_teis', 'lumicoins', TRUE),
    ('std_041', 'Marmita de Ontem', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_042', 'Café Frio', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_043', 'Bolo que Não Cresceu', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_044', 'Ovo Podre', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_045', 'Leite Vencido (3 dias)', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_046', 'Macarrão Instantâneo sem Tempero', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_047', 'Suco em Pó sem Água', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_048', 'Bala Derretida e Re-endurecida', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_049', 'Pipoca Queimada', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_050', 'Sanduíche Pisado', 'Item padrao da Loja Tosca.', 100, 'comida_ruim', 'lumicoins', TRUE),
    ('std_051', 'Pombo Raivoso', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_052', 'Barata Voadora', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_053', 'Mosquito Zika', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_054', 'Lesma Lenta', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_055', 'Sapo Atropelado (vivo, calma)', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_056', 'Rato de Esgoto', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_057', 'Carrapato Faminto', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_058', 'Pulga Saltitante', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_059', 'Minhoca Triste', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_060', 'Bicho de Pé', 'Item padrao da Loja Tosca.', 100, 'animais_toscos', 'lumicoins', TRUE),
    ('std_061', 'Espada de Plástico de Criança', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_062', 'Garfo Torto', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_063', 'Chinelo Havaianas (arma letal)', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_064', 'Vassoura Velha', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_065', 'Escova de Dente como Adaga', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_066', 'Régua de 30cm', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_067', 'Mata-Moscas', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_068', 'Pistola de Água Vazia', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_069', 'Boneco Inflável de Soco', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_070', 'Bumerangue que Não Volta', 'Item padrao da Loja Tosca.', 100, 'armas_rid_culas', 'lumicoins', TRUE),
    ('std_071', 'Boné Furado', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_072', 'Óculos com uma Lente', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_073', 'Relógio Parado (mas certo 2x/dia)', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_074', 'Corrente de Prata Falsa (na verdade é zinco)', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_075', 'Anel de Lata de Refrigerante', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_076', 'Pulseira de Macarrão', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_077', 'Gravata Manchada', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_078', 'Cinto que Não Fecha', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_079', 'Carteira Vazia', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_080', 'Chaveiro sem Chave', 'Item padrao da Loja Tosca.', 100, 'acess_rios_toscos', 'lumicoins', TRUE),
    ('std_081', 'Pedra Filosofal (na verdade é granito)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_082', 'Varinha Mágica de Pirulito', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_083', 'Poção do Amor (refrigerante de cola)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_084', 'Elixir da Vida (água da torneira)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_085', 'Cristal de Energia (vidro de garrafa)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_086', 'Pergaminho Antigo (papel queimado na vela)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_087', 'Amuleto de Proteção (botão de camisa)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_088', 'Pó de Fada (talco)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_089', 'Capa de Invisibilidade (lençol velho)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_090', 'Tapete Voador (capacho)', 'Item padrao da Loja Tosca.', 100, 'itens_m_gicos_falsos', 'lumicoins', TRUE),
    ('std_091', 'Espelho Quebrado', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_092', 'Gato Preto de Pelúcia', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_093', 'Guarda-chuva Aberto (dentro de casa)', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_094', 'Sal Derramado', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_095', 'Escada Para Passar Por Baixo', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_096', 'Sexta-feira 13 Engarrafada', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_097', 'Pé Frio', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_098', 'Boletim Escolar Vermelho', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_099', 'Fatura Atrasada', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_100', 'Notificação do Chefe', 'Item padrao da Loja Tosca.', 100, 'itens_de_azar', 'lumicoins', TRUE),
    ('std_101', 'Pedaço de Papelão', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_102', 'Elástico de Cabelo', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_103', 'Grampo Enferrujado', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_104', 'Botão Avulso', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_105', 'Meia sem Par', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_106', 'Tampinha de Caneta', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_107', 'Embalagem de Bala Vazia', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_108', 'Bilhete de Estacionamento (multa)', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_109', 'Cupom Vencido', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_110', 'Manual de Montagem Faltando Página', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_111', 'Parafuso Sobrando (de algum móvel)', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_112', 'Pilha de Roupa Suja', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_113', 'Travesseiro Achatado', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_114', 'Cobertor com Cheiro Estranho', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_115', 'Chinelo do Pé Esquerdo (par perdido)', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_116', 'Garrafa PET Vazia', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_117', 'Saco de Lixo Cheio', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_118', 'Caderno com Páginas Arrancadas', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_119', 'Pasta com Documentos Importantes (vazios)', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_120', 'Post-it Descolando', 'Item padrao da Loja Tosca.', 100, 'itens_aleat_rios', 'lumicoins', TRUE),
    ('std_121', 'Troféu de Participação', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_122', 'Medalha de "Quase Ganhou"', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_123', 'Certificado de Curso Não Concluído', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_124', 'Diploma Falsificado em Casa', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_125', 'Faixa de "Aniversariante" Usada', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_126', 'Coroa de Papel de Coroação Infantil', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_127', 'Estrela Dourada de Caderno', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_128', 'Adesivo de "Mandei Bem!"', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_129', 'Carimbo de "Visto"', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_130', 'Crachá de Visitante Vencido', 'Item padrao da Loja Tosca.', 100, 'itens_de_prest_gio_tosco', 'lumicoins', TRUE),
    ('std_131', 'Balão Murcho', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_132', 'Confete Já Usado', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_133', 'Bolo de Aniversário do Ano Passado', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_134', 'Vela de Aniversário Apagada', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_135', 'Chapéu de Festa Amassado', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_136', 'Língua de Sogra Estourada', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_137', 'Serpentina Enrolada no Ventilador', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_138', 'Convite de Festa que Ninguém Foi', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_139', 'Refrigerante Sem Gás', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_140', 'Salgadinho Murcho', 'Item padrao da Loja Tosca.', 100, 'itens_de_festa_toscos', 'lumicoins', TRUE),
    ('std_141', 'Caixa Misteriosa (tem só ar dentro)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_142', 'Item Lendário™ (escrito à mão)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_143', 'Baú do Tesouro (com boleto dentro)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_144', 'Chave Dourada (de lata pintada)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_145', 'Mapa do Tesouro (rabiscado a lápis)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_146', 'Bilhete Premiado (já sorteado, perdeu)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_147', 'Ovo de Dragão (na verdade é de galinha)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_148', 'Pedra Preciosa (achada no chão)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_149', 'Relíquia Ancestral (do bazar)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_150', 'Artefato Místico (controle remoto sem pilha)', 'Item padrao da Loja Tosca.', 100, 'itens_raros_na_verdade_n_o', 'lumicoins', TRUE),
    ('std_151', 'Crachá da Empresa Falida', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_152', 'Caneca "Melhor Chefe do Mundo" (presente forçado)', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_153', 'Calendário do Ano Passado', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_154', 'Grampeador sem Grampo', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_155', 'Post-it com Recado de 2019', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_156', 'Cabo HDMI que Não Serve', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_157', 'Mouse sem Pilha', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_158', 'Teclado com Tecla Faltando', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_159', 'Cadeira de Escritório que Range', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_160', 'E-mail Não Lido (847)', 'Item padrao da Loja Tosca.', 100, 'itens_de_trabalho_toscos', 'lumicoins', TRUE),
    ('std_161', 'Dúvida Existencial Engarrafada', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_162', 'Pacote de Ansiedade', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_163', 'Segunda-feira de Manhã', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_164', 'Fim de Semana que Passou Rápido', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_165', 'Despertador às 6h', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_166', 'Vontade de Desistir', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_167', 'Motivação (vencida)', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_168', 'Café da Manhã Pulado', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_169', 'Sono Atrasado', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_170', 'Procrastinação em Pó', 'Item padrao da Loja Tosca.', 100, 'itens_existenciais', 'lumicoins', TRUE),
    ('std_171', 'Wi-Fi Fraco', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_172', 'Vídeo que Não Carrega (Buffering Infinito)', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_173', 'Notificação de Spam', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_174', 'Captcha Impossível', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_175', 'Senha "123456"', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_176', 'Cabo de Carregador Embolado', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_177', 'Pop-up de Anúncio', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_178', 'Botão "X" do Anúncio (que não funciona)', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_179', 'Bateria 1% com Carregador Longe', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_180', 'Mensagem "Digitando..." que Nunca Chega', 'Item padrao da Loja Tosca.', 100, 'itens_de_internet', 'lumicoins', TRUE),
    ('std_181', 'Pedaço de Unha do Pé', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_182', 'Suor de Goleiro', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_183', 'Cheiro de Sovaco', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_184', 'Risada de Robô', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_185', 'Eco de um Arroto', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_186', 'Bafo de Manhã', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_187', 'Espirro Não Tampado', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_188', 'Soluço Persistente', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_189', 'Cócegas Engarrafadas', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_190', 'Sussurro de Vizinho Fofoqueiro', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_191', 'Olhar de Reprovação da Mãe', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_192', '"Já Vou" (que nunca vem)', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_193', 'Promessa de Dieta de Segunda', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_194', 'Resolução de Ano Novo (jan-fev apenas)', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_195', 'Última Vida do Celular', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_196', 'Tela Trincada (mas funciona)', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_197', 'Fone de Ouvido com um Lado Mudo', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_198', 'Carregador que Esquenta Muito', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_199', 'Wi-Fi do Vizinho (sem senha)', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE),
    ('std_200', 'Caixa Misteriosa Tosca (provavelmente é lixo mesmo)', 'Item padrao da Loja Tosca.', 100, 'itens_finais_bizarros', 'lumicoins', TRUE)
ON CONFLICT (item_key) DO UPDATE
SET item_name = EXCLUDED.item_name,
    item_description = EXCLUDED.item_description,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    currency_type = EXCLUDED.currency_type,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;

